/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_V1;

import Backend.DatabaseAccess;
import Backend.GeocodingExample;
import Backend.GoogleMap;
import org.json.simple.parser.ParseException;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Asus
 */
public class TransactionDetails extends javax.swing.JFrame {

    /**
     * Creates new form ManageAccount
     */
    public TransactionDetails(String TranID) {
        initComponents(TranID);
        jTable2.setRowHeight(40);
        jTable3.setRowHeight(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String TranID) {
        ArrayList<String> TransactionDetails = new ArrayList<String>();
        try {
            ResultSet rs = DatabaseAccess.SpecificTransaction_display(TranID);
            while (rs.next()) {
                TransactionDetails.add(rs.getString(1));
                TransactionDetails.add(rs.getString(2));
                TransactionDetails.add(rs.getString(3));
                TransactionDetails.add(rs.getString(4));
                TransactionDetails.add(rs.getString(5));
                TransactionDetails.add(rs.getString(6));
                TransactionDetails.add(rs.getString(7));
                TransactionDetails.add(rs.getString(8));
                TransactionDetails.add(rs.getString(9));
                TransactionDetails.add(rs.getString(10));
                TransactionDetails.add(rs.getString(11));
                TransactionDetails.add(rs.getString(12));
            }
            rs.close();
        }
        catch(SQLException ex){
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
        String devID = TransactionDetails.get(1);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Verofax");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-rounded-left.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-transaction-approved-32.png"))); // NOI18N
        jLabel3.setText("jLabel3");


        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-account-64.png"))); // NOI18N
        jLabel4.setText("jLabel4");


        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-list-50.png"))); // NOI18N


        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-product-24.png"))); // NOI18N
        jLabel126.setText("jLabel7");


        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-computer-30.png"))); // NOI18N
        jLabel16.setText("jLabel7");


        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel126)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Transaction Details");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Verofax");

        jLabel24.setText("Sign Out");


        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        jButton4.setText("Back");


        jButton5.setText("Check Temperature and Humidity");


        jButton3.setText("Check Location");


        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setPreferredSize(new java.awt.Dimension(1000, 1000));
        ArrayList<String> CoordList = DatabaseAccess.CurrentGPS(devID);
        ArrayList<String> Temp = DatabaseAccess.TemperatureGet(devID);
        ArrayList<String> Humi = DatabaseAccess.HumidityGet(devID);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {TransactionDetails.get(8), TransactionDetails.get(11), Temp.get(2), Humi.get(2), CoordList.get(0), CoordList.get(1)}
            },
            new String [] {
                "Delivery Address", "Delivery Funds", "Temperature", "Humidity", "Latitude", "Longitude"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row,int column) {
                if(column == 2||column == 3||column == 4||column == 5)
                    return false;
                else
                    return true;
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable3.setPreferredSize(new java.awt.Dimension(200, 300));
        jScrollPane5.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(400);
            jTable3.getColumnModel().getColumn(4).setResizable(false);
            jTable3.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {TransactionDetails.get(0), TransactionDetails.get(1), TransactionDetails.get(2), TransactionDetails.get(4), TransactionDetails.get(3), TransactionDetails.get(5), TransactionDetails.get(7)}
            },
            new String [] {
                "Transaction ID", "Device ID", "Sender Acc", "Product ID", "Pick Up Address", "Courier Acc", "Receiver Acc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            public boolean isCellEditable(int row,int column) {
                if(column == 0||column == 1)
                    return false;
                else
                    return true;
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable2.setPreferredSize(new java.awt.Dimension(200, 300));
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(400);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        Timer t = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String[] updateTable = {"Volvo", "BMW"};
                try {
                    ResultSet rs = DatabaseAccess.SpecificTransaction_display(TranID);
                    while (rs.next()) {
                        updateTable[0]=rs.getString(9);
                        updateTable[1]=rs.getString(12);
                    }
                    rs.close();
                }
                catch(SQLException ex){
                    System.out.println("SQLException: " + ex.getMessage());
                    System.out.println("SQLState: " + ex.getSQLState());
                    System.out.println("VendorError: " + ex.getErrorCode());
                }
                ArrayList<String> CoordList = DatabaseAccess.CurrentGPS(devID);
                ArrayList<String> Temp = DatabaseAccess.TemperatureGet(devID);
                ArrayList<String> Humi = DatabaseAccess.HumidityGet(devID);
                jTable3.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {updateTable[0], updateTable[1], Temp.get(2), Humi.get(2), CoordList.get(0), CoordList.get(1)}
                        },
                        new String [] {
                                "Delivery Address", "Delivery Funds", "Temperature", "Humidity", "Latitude", "Longitude"
                        }
                ) {
                    Class[] types = new Class [] {
                            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                            true, true, false, true, true, true
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int row,int column) {
                        if(column == 2||column == 3||column == 4||column == 5)
                            return false;
                        else
                            return true;
                    }
                });
                if (jTable3.getColumnModel().getColumnCount() > 0) {
                    jTable3.getColumnModel().getColumn(0).setPreferredWidth(400);
                    jTable3.getColumnModel().getColumn(4).setResizable(false);
                    jTable3.getColumnModel().getColumn(5).setResizable(false);
                }
                jTable3.getModel().addTableModelListener(new TableModelListener() {
                    @Override
                    public void tableChanged(TableModelEvent e) {
                        try {
                            table3Edit(e,TranID);
                        } catch (IOException ioException) {
                            ioException.printStackTrace();
                        } catch (ParseException parseException) {
                            parseException.printStackTrace();
                        } catch (InterruptedException interruptedException) {
                            interruptedException.printStackTrace();
                        }
                    }
                });
            };
        });
        t.start();
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt,devID,TranID,t);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt,t);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt,devID,TranID,t);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (ParseException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt,t);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt,t);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt,t);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt,t);
            }
        });
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt,t);
            }
        });
        jLabel126.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel126MouseClicked(evt,t);
            }
        });
        jTable2.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                table2Edit(e,TranID);
            }
        });
        jTable3.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                try {
                    table3Edit(e,TranID);
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                } catch (ParseException parseException) {
                    parseException.printStackTrace();
                } catch (InterruptedException interruptedException) {
                    interruptedException.printStackTrace();
                }
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    public void table2Edit(TableModelEvent e,String TranID) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        TableModel model = (TableModel)e.getSource();
        String data = (String) model.getValueAt(row, column);
        System.out.println(data);
        if (column == 2)
        {
            DatabaseAccess.Transaction_edit("senderAcc = '"+data+"'",TranID);
        }
        else if (column == 3)
        {
            DatabaseAccess.Transaction_edit("productID = '"+data+"'",TranID);
        }
        else if (column == 4)
        {
            DatabaseAccess.Transaction_edit("pickupAddress = '"+data+"'",TranID);
        }
        else if (column == 5)
        {
            DatabaseAccess.Transaction_edit("courierAcc = '"+data+"'",TranID);
        }
        else if (column == 6)
        {
            DatabaseAccess.Transaction_edit("receiverAcc = '"+data+"'",TranID);
        }
    }
    public void table3Edit(TableModelEvent e,String TranID) throws IOException, ParseException, InterruptedException {
        int row = e.getFirstRow();
        int column = e.getColumn();
        TableModel model = (TableModel)e.getSource();
        String data = (String) model.getValueAt(row, column);
        System.out.println(data);
        if (column == 0)
        {
            DatabaseAccess.Transaction_edit("deliveryAddress = '"+data+"'",TranID);
            String geocode = GeocodingExample.Geocode(data);
            DatabaseAccess.Transaction_edit("deliveryCoord = '"+geocode+"'",TranID);
        }
        else if (column == 1)
        {
            DatabaseAccess.Transaction_edit("deliveryFunds = '"+data+"'",TranID);
        }
    }
    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel24MouseClicked

        // TODO add your handling code here:
        int YesOrNo;
        YesOrNo = JOptionPane.showConfirmDialog(null, "Do you comfirm to sign out?","No",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
        Login_Page lp2 = new Login_Page();
        lp2.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
            t.stop();
        dispose();
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Manage_Account m = new Manage_Account();
        m.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ManageTransaction mt = new ManageTransaction();
        mt.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt,Timer t) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         ManageTransaction mt = new ManageTransaction();
        mt.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel126MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel126MouseClicked
        // TODO add your handling code here:
        View_Product vp = new View_Product();
        vp.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jLabel126MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt,String a,String TranID,Timer t) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Temperature_Tracking vp = new Temperature_Tracking(a,TranID);
        vp.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt,String devID,String TranID,Timer t) throws IOException, ParseException, InterruptedException {//GEN-FIRST:event_jButton3ActionPerformed
        GoogleMap vp = new GoogleMap(devID,TranID);
        vp.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Dashboard da = new Dashboard();
        da.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt,Timer t) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        View_Devices vp = new View_Devices();
        vp.setVisible(true);
        JFrame frame = new JFrame();
        frame.setVisible(false);
        t.stop();
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
